project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"       # Render all Quarto files
    - "!README.md"  # Explicitly tell Quarto to ignore the README

website:
  title: "The Replication Observatory"
  description: "A living report on journal replication outcomes."
  page-footer: 
    left: "Data provided by FLoRA and FORRT."
    right: "Updated automatically."

format:
  html:
    theme:
      light: [cosmo, styles.css]
      dark: [darkly, styles.css]
    toc: true
    toc-title: "Navigation"
    css: styles.css